# Prometheus configuration for Model Card Generator monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'development'
    service: 'modelcard-generator'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Model Card Generator application metrics
  - job_name: 'modelcard-generator'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Docker container metrics (if using cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Application health checks
  - job_name: 'health-checks'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 5s

  # ML platform integrations (if available)
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
    metrics_path: '/metrics'
    scrape_interval: 60s
    honor_labels: true

  # Redis metrics (if using Redis)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

# Remote storage configuration (optional)
# remote_write:
#   - url: "https://your-remote-storage/api/v1/write"
#     headers:
#       Authorization: "Bearer your-token"

# Remote read configuration (optional)
# remote_read:
#   - url: "https://your-remote-storage/api/v1/read"
#     headers:
#       Authorization: "Bearer your-token"