apiVersion: v1
kind: Service
metadata:
  name: modelcard-service
  namespace: modelcard-system
  labels:
    app: modelcard-generator
spec:
  selector:
    app: modelcard-generator
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
